create database StoreDB;
go

create schema Store;
go

create table Products
(
   ProductsID int not null identity primary key
   Name nvarchar(50) not null, --char, varchar, nchar, nvarchar, nvarcharmax
   Price char(50) not null-- we don't want the primary key to be null 
   -- identity() takes seed-start and step--increment
   -- primary key means indexing, indexing means you are setting a unique identifier
   -- if you index every column there will be a larger set of meta data
   --simple insert 
   insert into Employee
   values('jas', 'Broming', '12385435', '3652')
   values('Had', 'tud', '12323225', '34')
   values('Hackman', 'fan', '123212135', '866')
   go


)

 insert into Product
   values('IPhone', '200')
   go

   
 insert into Customers
   values('Tina', 'Smith', '224321332433434')
   go

create table Orders
(
   OrderID int not null identity primary key
   ProductID int not null identity foreign key,
   CustomerID int not null identity foreign key
   -- we don't want the primary key to be null 
   -- identity() takes seed-start and step--increment
   -- primary key means indexing, indexing means you are setting a unique identifier
   -- if you index every column there will be a larger set of meta data

)

--create view of order where Tina bought an Iphone
SELECT Name = 'IPhone'
FROM Products
WHERE FirstName = 'Tina' AND LastName = 'Smith'

--report all orders of Tina
SELECT OrderID
FROM Orders
WHERE FirstName = 'Tina' AND LastName = 'Smith'

--report all revenue generated by sales of IPhone
SELECT SUM(Price)
FROM Orders
[WHERE Name = 'IPHONE'];

--increase price of IPhone to 250
UPDATE Products   
SET Price = { '250' }
FROM Products
WHERE Name = {'IPHONE'}
go


insert into EmpDetails
values('haoj', 'coom', '87612135', '322')
values('jos', 'avem', '893223135', '464')
values('mant', 'Barm', '533212135', '954')
go


create table Customers
(
   CustomerID int not null identity primary key
   Firstname nvarchar (50) not null,
   Lastname nvarchar (50) not null,
   CardNumber int (50) not null
   -- we don't want the primary key to be null 
   -- identity() takes seed-start and step--increment
   -- primary key means indexing, indexing means you are setting a unique identifier
   -- if you index every column there will be a larger set of meta data

)

insert into Customers
values('uye', 'ahm', '6612135', '652')
values('yen', 'corn', '3443135', '122')
values('om', 'hasom', '983212135', '982')
go